volumes:
  pg_data:

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB_NAME' ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - postgres
      - -c
      - max_connections=200

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres